import { Product } from "../../models";

const seededAt = "2026-04-28T00:00:00.000Z";

const products: Product[] = [
  {
    id: "product-1",
    name: "Bombilla Alpaca boca ancha",
    internalCode: "ALEM-BOM-001",
    barcode: "779000100001",
    category: "Bombillas",
    salePrice: 790,
    cost: 430,
    description: "Bombilla de alpaca con caño fino y boca ancha.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-2",
    name: "Mate Camionero",
    internalCode: "ALEM-MAT-001",
    barcode: "779000100002",
    category: "Calabaza",
    salePrice: 890,
    cost: 490,
    description: "Mate camionero de calabaza trabajado artesanalmente.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-3",
    name: "Matera de Auto Cuero con manija mod0024",
    internalCode: "ALEM-MTE-001",
    barcode: "779000100003",
    category: "Materas",
    salePrice: 1890,
    cost: 1040,
    description: "Matera de auto en cuero con manija.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-4",
    name: "Mate Imperial Cerámica",
    internalCode: "ALEM-MAT-002",
    barcode: "779000100004",
    category: "Ceramica",
    salePrice: 2750,
    cost: 1510,
    description: "Mate imperial de cerámica.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-5",
    name: "Mate Pulido",
    internalCode: "ALEM-MAT-003",
    barcode: "779000100005",
    category: "Calabaza",
    salePrice: 650,
    cost: 360,
    description: "Mate de calabaza pulido.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-6",
    name: "Mate Cerámica",
    internalCode: "ALEM-MAT-004",
    barcode: "779000100006",
    category: "Ceramica",
    salePrice: 690,
    cost: 380,
    description: "Mate de cerámica para uso diario.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-7",
    name: "Mate Imperial calabaza cincelado",
    internalCode: "ALEM-MAT-005",
    barcode: "779000100007",
    category: "Calabaza",
    salePrice: 2850,
    cost: 1570,
    description: "Mate imperial de calabaza cincelado.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-8",
    name: "Mate Alpaca y Oro",
    internalCode: "ALEM-MAT-006",
    barcode: "779000100008",
    category: "Calabaza",
    salePrice: 3490,
    cost: 1920,
    description: "Mate con terminaciones en alpaca y oro.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-9",
    name: "Bombilla Alpaca y Oro",
    internalCode: "ALEM-BOM-002",
    barcode: "779000100009",
    category: "Bombillas",
    salePrice: 1690,
    cost: 930,
    description: "Bombilla de alpaca y oro elaborada artesanalmente.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-10",
    name: "Bombilla Plata Lisa",
    internalCode: "ALEM-BOM-003",
    barcode: "779000100010",
    category: "Bombillas",
    salePrice: 6290,
    cost: 3460,
    description: "Bombilla de plata lisa.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-11",
    name: "Bombilla Alpaca boca fina",
    internalCode: "ALEM-BOM-004",
    barcode: "779000100011",
    category: "Bombillas",
    salePrice: 790,
    cost: 435,
    description: "Bombilla de alpaca con boca fina.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-12",
    name: "Bombilla Alpaca con Tarjeta bronce",
    internalCode: "ALEM-BOM-005",
    barcode: "779000100012",
    category: "Bombillas",
    salePrice: 890,
    cost: 490,
    description: "Bombilla de alpaca con tarjeta en bronce.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-13",
    name: "Bombilla Alpaca Resorte",
    internalCode: "ALEM-BOM-006",
    barcode: "779000100013",
    category: "Bombillas",
    salePrice: 890,
    cost: 490,
    description: "Bombilla de alpaca con filtro resorte.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-14",
    name: "Bombillon Alpaca",
    internalCode: "ALEM-BOM-007",
    barcode: "779000100014",
    category: "Bombillas",
    salePrice: 990,
    cost: 545,
    description: "Bombillon de alpaca para mate.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-15",
    name: "Bombillon Alpaca Resorte",
    internalCode: "ALEM-BOM-008",
    barcode: "779000100015",
    category: "Bombillas",
    salePrice: 1100,
    cost: 605,
    description: "Bombillon de alpaca con filtro resorte.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-16",
    name: "Bombillon Alpaca boca ancha",
    internalCode: "ALEM-BOM-009",
    barcode: "779000100016",
    category: "Bombillas",
    salePrice: 1100,
    cost: 605,
    description: "Bombillon de alpaca con boca ancha.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-17",
    name: "Bombillon Alpaca con Tarjeta bronce",
    internalCode: "ALEM-BOM-010",
    barcode: "779000100017",
    category: "Bombillas",
    salePrice: 1100,
    cost: 605,
    description: "Bombillon de alpaca con tarjeta en bronce.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-18",
    name: "Bombillon Alpaca y Oro",
    internalCode: "ALEM-BOM-011",
    barcode: "779000100018",
    category: "Bombillas",
    salePrice: 1890,
    cost: 1040,
    description: "Bombillon de alpaca y oro elaborado artesanalmente.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-19",
    name: "Mate Torpedo",
    internalCode: "ALEM-MAT-007",
    barcode: "779000100019",
    category: "Calabaza",
    salePrice: 690,
    cost: 380,
    description: "Mate torpedo de calabaza.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-20",
    name: "Mate torpedo dibujado",
    internalCode: "ALEM-MAT-008",
    barcode: "779000100020",
    category: "Calabaza",
    salePrice: 890,
    cost: 490,
    description: "Mate torpedo de calabaza con dibujo.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-21",
    name: "Mate Camionero Copa",
    internalCode: "ALEM-MAT-009",
    barcode: "779000100021",
    category: "Calabaza",
    salePrice: 920,
    cost: 506,
    description: "Mate camionero copa de calabaza.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-22",
    name: "Mate Semi Imperial Calabaza",
    internalCode: "ALEM-MAT-010",
    barcode: "779000100022",
    category: "Calabaza",
    salePrice: 1990,
    cost: 1095,
    description: "Mate semi imperial de calabaza.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-23",
    name: "Mate Imperial calabaza",
    internalCode: "ALEM-MAT-011",
    barcode: "779000100023",
    category: "Calabaza",
    salePrice: 2750,
    cost: 1513,
    description: "Mate imperial de calabaza.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-24",
    name: "Mate Plata y Oro cincelado Premium",
    internalCode: "ALEM-MAT-012",
    barcode: "779000100024",
    category: "Calabaza",
    salePrice: 6890,
    cost: 3790,
    description: "Mate premium con plata, oro y cincelado.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-25",
    name: "Mate Plata y Oro Premium",
    internalCode: "ALEM-MAT-013",
    barcode: "779000100025",
    category: "Calabaza",
    salePrice: 7990,
    cost: 4395,
    description: "Mate premium con terminaciones en plata y oro.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-26",
    name: "Mate Plata Premium",
    internalCode: "ALEM-MAT-014",
    barcode: "779000100026",
    category: "Calabaza",
    salePrice: 16590,
    cost: 9125,
    description: "Mate premium con terminaciones en plata.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-27",
    name: "Mate Imperial Plata y Oro Premium con 2 iniciales de Oro",
    internalCode: "ALEM-MAT-015",
    barcode: "779000100027",
    category: "Calabaza",
    salePrice: 20590,
    cost: 11325,
    description: "Mate imperial premium en plata y oro con iniciales.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-28",
    name: "Mate Ceramica Barril",
    internalCode: "ALEM-MAT-016",
    barcode: "779000100028",
    category: "Ceramica",
    salePrice: 590,
    cost: 325,
    description: "Mate de ceramica con formato barril.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-29",
    name: "Mate Imperial Ceramica cincelado",
    internalCode: "ALEM-MAT-017",
    barcode: "779000100029",
    category: "Ceramica",
    salePrice: 2850,
    cost: 1568,
    description: "Mate imperial de ceramica cincelado.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-30",
    name: "Mate Imperial Ceramica cincelado especial",
    internalCode: "ALEM-MAT-018",
    barcode: "779000100030",
    category: "Ceramica",
    salePrice: 2990,
    cost: 1645,
    description: "Mate imperial de ceramica con cincelado especial.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-31",
    name: "Mate madera Imperial",
    internalCode: "ALEM-MAT-019",
    barcode: "779000100031",
    category: "Mates",
    salePrice: 3290,
    cost: 1810,
    description: "Mate imperial de madera.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-32",
    name: "Matera de Auto en Madera",
    internalCode: "ALEM-MTE-002",
    barcode: "779000100032",
    category: "Materas",
    salePrice: 990,
    cost: 545,
    description: "Matera de auto fabricada en madera.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-33",
    name: "Matera Simil cuero",
    internalCode: "ALEM-MTE-003",
    barcode: "779000100033",
    category: "Materas",
    salePrice: 1290,
    cost: 710,
    description: "Matera en simil cuero.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-34",
    name: "Matera simil con gamuza",
    internalCode: "ALEM-MTE-004",
    barcode: "779000100034",
    category: "Materas",
    salePrice: 1390,
    cost: 765,
    description: "Matera en simil cuero con gamuza.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  },
  {
    id: "product-35",
    name: "Matera gamuza y madera",
    internalCode: "ALEM-MTE-005",
    barcode: "779000100035",
    category: "Materas",
    salePrice: 1750,
    cost: 963,
    description: "Matera combinada en gamuza y madera.",
    imageUrl: "",
    status: "active",
    createdAt: seededAt,
    updatedAt: seededAt
  }
];

export const productsStorage = {
  findAll: () => products,

  findById: (id: string) => products.find((product) => product.id === id),

  create: (product: Product) => {
    products.push(product);
    return product;
  },

  update: (id: string, payload: Partial<Product>) => {
    const product = products.find((item) => item.id === id);

    if (!product) {
      return null;
    }

    Object.assign(product, payload, { id });

    return product;
  }
};
